language: php

cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - $HOME/.composer/cache
    - vendor

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - TESTBENCH_VERSION=3.4.* DATABASE_VERSION=3.4.*@dev ILLUMINATE_VERSION=5.4.*

before_install:
  - composer global require hirak/prestissimo
  - composer require phpunit/phpunit
  - composer require "illuminate/support:${ILLUMINATE_VERSION}"
  - composer require "orchestra/database:${DATABASE_VERSION}"
  - composer require "orchestra/testbench:${TESTBENCH_VERSION}"

install: composer update --no-interaction

script: vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/coveralls

notifications:
  email: false
